### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by thefoxie** [carloslfu/figma-app-linux#1]
There's no figma icon, only some electron generic one.
![image](https://user-images.githubusercontent.com/15309350/45140319-ad9f6680-b1b2-11e8-8d1b-17a96bdcafb2.png)

**Comment by carloslfu** [comment]
Thanks, I'll configure that.

**Comment by winstonford** [comment]
Attached is Figma.zip file which includes:

1. Figma png icons extracted from the figma.icns package included in the Figma mac app.
2. Figma icons rescaled and exported in Figma, to adhere to both macOS and elementaryOS human interface guidelines which calls for an 8 pixel grid with specified whitespace.
2. Instructions on how to install Figma appimage released in this repo with AppimageLauncher, which integrates the app into the os, as shown in the screenshot below.

@carloslfu thanks for the great work! Perhaps you can include the rescaled icons in your release. In the meantime, I explain how to add them manually.  I can also share a link to the Figma icons.

Also for anyone running elementaryOS on a mac, I released a utility called [Mac Rambo](https://github.com/winstonford/mac-rambo) called which enables the command key so that you can command scroll to zoom in Figma.

![figma-appimage-elementary-juno](https://user-images.githubusercontent.com/4634622/53206640-8244f280-35ff-11e9-8121-1fc906b9c5fb.png)
[Figma.zip](https://github.com/carloslfu/figma-app-linux/files/2891585/Figma.zip)

**Comment by carloslfu** [comment]
Fixed in https://github.com/carloslfu/figma-app-linux/releases/tag/v4, thanks @winstonford and @thefoxie.
